version: "3.1"

services:
  postgres:
    image: postgres:latest
    container_name: rotina-compartilhamento-fastapi-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
